apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: friendlyhello
spec:
    replicas: 2
    template:
        metadata:
            labels:
                app: friendlyhello
        spec:
            containers:
            - name: frihellctn
              image: ruiwang111/friendlyhello:v1
              ports:
              - containerPort: 80
